/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.winwinkit.client.models.AffiliateAnalyticsMetrics

class AffiliateAnalyticsMetricsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AffiliateAnalyticsMetrics
        //val modelInstance = AffiliateAnalyticsMetrics()

        // to test the property `claims` - The number of times the affiliate's codes were claimed
        should("test claims") {
            // uncomment below to test the property
            //modelInstance.claims shouldBe ("TODO")
        }

        // to test the property `conversions` - The number of claims that converted into a purchase
        should("test conversions") {
            // uncomment below to test the property
            //modelInstance.conversions shouldBe ("TODO")
        }

        // to test the property `revenue` - The revenue attributed to the affiliate, in USD cents
        should("test revenue") {
            // uncomment below to test the property
            //modelInstance.revenue shouldBe ("TODO")
        }

        // to test the property `earnings` - The commission owed to the affiliate on that revenue, in USD cents
        should("test earnings") {
            // uncomment below to test the property
            //modelInstance.earnings shouldBe ("TODO")
        }

    }
}
