/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.winwinkit.client.models.AffiliatePlatform

class AffiliatePlatformTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AffiliatePlatform
        //val modelInstance = AffiliatePlatform()

        // to test the property `type` - The platform type
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `handle` - The public handle/username on the platform
        should("test handle") {
            // uncomment below to test the property
            //modelInstance.handle shouldBe ("TODO")
        }

        // to test the property `verified` - Whether ownership of the platform has been verified
        should("test verified") {
            // uncomment below to test the property
            //modelInstance.verified shouldBe ("TODO")
        }

    }
}
