/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.winwinkit.client.models.AffiliateAnalyticsEntry
import com.winwinkit.client.models.AffiliateAnalyticsMetrics

class AffiliateAnalyticsEntryTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AffiliateAnalyticsEntry
        //val modelInstance = AffiliateAnalyticsEntry()

        // to test the property `id` - The affiliate id
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `name` - The affiliate name
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `acceptedAt` - When the affiliate joined the project
        should("test acceptedAt") {
            // uncomment below to test the property
            //modelInstance.acceptedAt shouldBe ("TODO")
        }

        // to test the property `status` - The affiliate current standing with the project. Not always `approved`: an affiliate is reported for what they did in the period, so one since banned or deactivated still appears alongside the metrics they earned.
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `totals` - The affiliate's totals over the period
        should("test totals") {
            // uncomment below to test the property
            //modelInstance.totals shouldBe ("TODO")
        }

    }
}
