/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.winwinkit.client.models.AffiliateAnalytics
import com.winwinkit.client.models.AffiliateAnalyticsEntry
import com.winwinkit.client.models.AffiliateAnalyticsMetrics
import com.winwinkit.client.models.Pagination

class AffiliateAnalyticsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AffiliateAnalytics
        //val modelInstance = AffiliateAnalytics()

        // to test the property `from` - The first day of the period, inclusive
        should("test from") {
            // uncomment below to test the property
            //modelInstance.from shouldBe ("TODO")
        }

        // to test the property `to` - The last day of the period, inclusive
        should("test to") {
            // uncomment below to test the property
            //modelInstance.to shouldBe ("TODO")
        }

        // to test the property `totals` - The totals across every affiliate in the period, not just this page
        should("test totals") {
            // uncomment below to test the property
            //modelInstance.totals shouldBe ("TODO")
        }

        // to test the property `affiliates` - The page of affiliates, oldest joiner first. Affiliates with no activity in the period are omitted.
        should("test affiliates") {
            // uncomment below to test the property
            //modelInstance.affiliates shouldBe ("TODO")
        }

        // to test the property `pagination` - Where this page sits within the affiliates that matched
        should("test pagination") {
            // uncomment below to test the property
            //modelInstance.pagination shouldBe ("TODO")
        }

    }
}
