/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.winwinkit.client.models.AppStorePrice

class AppStorePriceTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AppStorePrice
        //val modelInstance = AppStorePrice()

        // to test the property `territory` - The price territory.
        should("test territory") {
            // uncomment below to test the property
            //modelInstance.territory shouldBe ("TODO")
        }

        // to test the property `price` - The price amount.
        should("test price") {
            // uncomment below to test the property
            //modelInstance.price shouldBe ("TODO")
        }

        // to test the property `currency` - The price currency.
        should("test currency") {
            // uncomment below to test the property
            //modelInstance.currency shouldBe ("TODO")
        }

    }
}
