/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.winwinkit.client.models.AppStoreSubscription
import com.winwinkit.client.models.AppStorePrice

class AppStoreSubscriptionTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AppStoreSubscription
        //val modelInstance = AppStoreSubscription()

        // to test the property `id` - The subscription id.
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `productId` - The product id.
        should("test productId") {
            // uncomment below to test the property
            //modelInstance.productId shouldBe ("TODO")
        }

        // to test the property `name` - The subscription name.
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `subscriptionPeriod` - The subscription period.
        should("test subscriptionPeriod") {
            // uncomment below to test the property
            //modelInstance.subscriptionPeriod shouldBe ("TODO")
        }

        // to test the property `prices` - The prices of the subscription.
        should("test prices") {
            // uncomment below to test the property
            //modelInstance.prices shouldBe ("TODO")
        }

    }
}
