/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.winwinkit.client.models.AppStoreOfferCode
import com.winwinkit.client.models.AppStorePrice

class AppStoreOfferCodeTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AppStoreOfferCode
        //val modelInstance = AppStoreOfferCode()

        // to test the property `id` - The offer code id.
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `name` - The offer code name.
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `customerEligibilities` - The offer code customer eligibilities.
        should("test customerEligibilities") {
            // uncomment below to test the property
            //modelInstance.customerEligibilities shouldBe ("TODO")
        }

        // to test the property `offerEligibility` - The offer code offer eligibility.
        should("test offerEligibility") {
            // uncomment below to test the property
            //modelInstance.offerEligibility shouldBe ("TODO")
        }

        // to test the property `duration` - The offer code duration.
        should("test duration") {
            // uncomment below to test the property
            //modelInstance.duration shouldBe ("TODO")
        }

        // to test the property `offerMode` - The offer code offer mode.
        should("test offerMode") {
            // uncomment below to test the property
            //modelInstance.offerMode shouldBe ("TODO")
        }

        // to test the property `numberOfPeriods` - The offer code number of periods.
        should("test numberOfPeriods") {
            // uncomment below to test the property
            //modelInstance.numberOfPeriods shouldBe ("TODO")
        }

        // to test the property `prices` - The offer code prices.
        should("test prices") {
            // uncomment below to test the property
            //modelInstance.prices shouldBe ("TODO")
        }

    }
}
