/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.winwinkit.client.models.CodeReferralUser

class CodeReferralUserTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CodeReferralUser
        //val modelInstance = CodeReferralUser()

        // to test the property `appUserId` - The app user id of the referral code owner
        should("test appUserId") {
            // uncomment below to test the property
            //modelInstance.appUserId shouldBe ("TODO")
        }

    }
}
