/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.winwinkit.client.models.CodeEntity
import com.winwinkit.client.models.AffiliatePlatform
import com.winwinkit.client.models.CodeAffiliate
import com.winwinkit.client.models.CodePromoCode
import com.winwinkit.client.models.CodeReferralUser

class CodeEntityTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CodeEntity
        //val modelInstance = CodeEntity()

        // to test the property `name` - The affiliate name
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `logoUrl` - The affiliate logo url
        should("test logoUrl") {
            // uncomment below to test the property
            //modelInstance.logoUrl shouldBe ("TODO")
        }

        // to test the property `platforms` - The affiliate social platforms
        should("test platforms") {
            // uncomment below to test the property
            //modelInstance.platforms shouldBe ("TODO")
        }

        // to test the property `limit` - The maximum number of times the code can be claimed (0 = unlimited)
        should("test limit") {
            // uncomment below to test the property
            //modelInstance.limit shouldBe ("TODO")
        }

        // to test the property `appUserId` - The app user id of the referral code owner
        should("test appUserId") {
            // uncomment below to test the property
            //modelInstance.appUserId shouldBe ("TODO")
        }

    }
}
