/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.winwinkit.client.models.Code
import com.winwinkit.client.models.CodeEntity
import com.winwinkit.client.models.ReceiverRewards

class CodeTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Code
        //val modelInstance = Code()

        // to test the property `type` - The resolved code type
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `code` - The code
        should("test code") {
            // uncomment below to test the property
            //modelInstance.code shouldBe ("TODO")
        }

        // to test the property `isActive` - Whether the code is active and can be claimed
        should("test isActive") {
            // uncomment below to test the property
            //modelInstance.isActive shouldBe ("TODO")
        }

        // to test the property `entity`
        should("test entity") {
            // uncomment below to test the property
            //modelInstance.entity shouldBe ("TODO")
        }

        // to test the property `rewards` - The rewards granted to the user claiming the code
        should("test rewards") {
            // uncomment below to test the property
            //modelInstance.rewards shouldBe ("TODO")
        }

    }
}
