/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.winwinkit.client.models.CodePromoCode

class CodePromoCodeTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CodePromoCode
        //val modelInstance = CodePromoCode()

        // to test the property `limit` - The maximum number of times the code can be claimed (0 = unlimited)
        should("test limit") {
            // uncomment below to test the property
            //modelInstance.limit shouldBe ("TODO")
        }

    }
}
