/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.winwinkit.client.models.GooglePlayPromoCodeValue

class GooglePlayPromoCodeValueTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GooglePlayPromoCodeValue
        //val modelInstance = GooglePlayPromoCodeValue()

        // to test the property ``value`` - The promo code value
        should("test `value`") {
            // uncomment below to test the property
            //modelInstance.`value` shouldBe ("TODO")
        }

        // to test the property `expiresAt` - The promo code value expiration date
        should("test expiresAt") {
            // uncomment below to test the property
            //modelInstance.expiresAt shouldBe ("TODO")
        }

    }
}
