/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.winwinkit.client.models.OfferCodeResponseData
import com.winwinkit.client.models.AppStoreOfferCode
import com.winwinkit.client.models.AppStoreSubscription

class OfferCodeResponseDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OfferCodeResponseData
        //val modelInstance = OfferCodeResponseData()

        // to test the property `offerCode` - The offer code
        should("test offerCode") {
            // uncomment below to test the property
            //modelInstance.offerCode shouldBe ("TODO")
        }

        // to test the property `subscription` - The subscription
        should("test subscription") {
            // uncomment below to test the property
            //modelInstance.subscription shouldBe ("TODO")
        }

    }
}
