/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.winwinkit.client.models.OfferCodeReward

class OfferCodeRewardTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OfferCodeReward
        //val modelInstance = OfferCodeReward()

        // to test the property `key` - The key of the reward
        should("test key") {
            // uncomment below to test the property
            //modelInstance.key shouldBe ("TODO")
        }

        // to test the property `offerCodeId` - The offer code id
        should("test offerCodeId") {
            // uncomment below to test the property
            //modelInstance.offerCodeId shouldBe ("TODO")
        }

        // to test the property `offerCodeRefName` - The offer code reference name that is set in the App Store Connect
        should("test offerCodeRefName") {
            // uncomment below to test the property
            //modelInstance.offerCodeRefName shouldBe ("TODO")
        }

        // to test the property `subscriptionProductId` - The subscription product id of the offer code
        should("test subscriptionProductId") {
            // uncomment below to test the property
            //modelInstance.subscriptionProductId shouldBe ("TODO")
        }

        // to test the property `name` - The name of the reward
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `description` - The description of the reward
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `metadata` - The metadata of the reward
        should("test metadata") {
            // uncomment below to test the property
            //modelInstance.metadata shouldBe ("TODO")
        }

        // to test the property `createdAt` - The created at of the reward
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `updatedAt` - The updated at of the reward
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

    }
}
