/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.winwinkit.client.models.ReceiverRewards
import com.winwinkit.client.models.ReceiverBasicReward
import com.winwinkit.client.models.ReceiverCreditReward
import com.winwinkit.client.models.ReceiverGooglePlayPromoCodeReward
import com.winwinkit.client.models.ReceiverOfferCodeReward
import com.winwinkit.client.models.ReceiverRevenueCatEntitlementReward
import com.winwinkit.client.models.ReceiverRevenueCatOfferingReward

class ReceiverRewardsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ReceiverRewards
        //val modelInstance = ReceiverRewards()

        // to test the property `basic` - The basic rewards
        should("test basic") {
            // uncomment below to test the property
            //modelInstance.basic shouldBe ("TODO")
        }

        // to test the property `credit` - The credit rewards
        should("test credit") {
            // uncomment below to test the property
            //modelInstance.credit shouldBe ("TODO")
        }

        // to test the property `offerCode` - The offer code rewards
        should("test offerCode") {
            // uncomment below to test the property
            //modelInstance.offerCode shouldBe ("TODO")
        }

        // to test the property `googleplayPromoCode` - The Google Play promo code rewards
        should("test googleplayPromoCode") {
            // uncomment below to test the property
            //modelInstance.googleplayPromoCode shouldBe ("TODO")
        }

        // to test the property `revenuecatEntitlement` - The RevenueCat entitlement rewards
        should("test revenuecatEntitlement") {
            // uncomment below to test the property
            //modelInstance.revenuecatEntitlement shouldBe ("TODO")
        }

        // to test the property `revenuecatOffering` - The RevenueCat offering rewards
        should("test revenuecatOffering") {
            // uncomment below to test the property
            //modelInstance.revenuecatOffering shouldBe ("TODO")
        }

    }
}
