/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.winwinkit.client.models.ReferralProgramRewards
import com.winwinkit.client.models.ReferralProgramReceiverRewards
import com.winwinkit.client.models.ReferralProgramSenderRewards

class ReferralProgramRewardsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ReferralProgramRewards
        //val modelInstance = ReferralProgramRewards()

        // to test the property `sender` - The program sender rewards
        should("test sender") {
            // uncomment below to test the property
            //modelInstance.sender shouldBe ("TODO")
        }

        // to test the property ``receiver`` - The program receiver rewards
        should("test `receiver`") {
            // uncomment below to test the property
            //modelInstance.`receiver` shouldBe ("TODO")
        }

    }
}
