/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.winwinkit.client.models.ReferralProgram
import com.winwinkit.client.models.ReferralProgramRewards

class ReferralProgramTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ReferralProgram
        //val modelInstance = ReferralProgram()

        // to test the property `id` - The program id
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `name` - The program name
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `description` - The program description
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `metadata` - The program metadata
        should("test metadata") {
            // uncomment below to test the property
            //modelInstance.metadata shouldBe ("TODO")
        }

        // to test the property `distributionPercentage` - The program distribution percentage
        should("test distributionPercentage") {
            // uncomment below to test the property
            //modelInstance.distributionPercentage shouldBe ("TODO")
        }

        // to test the property `limit` - The program limit
        should("test limit") {
            // uncomment below to test the property
            //modelInstance.limit shouldBe ("TODO")
        }

        // to test the property `rewards` - The program rewards
        should("test rewards") {
            // uncomment below to test the property
            //modelInstance.rewards shouldBe ("TODO")
        }

        // to test the property `createdAt` - The program created at
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `updatedAt` - The program updated at
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

    }
}
