/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.winwinkit.client.models.ReferralProgramReceiverRewards
import com.winwinkit.client.models.ReferralProgramReceiverBasicReward
import com.winwinkit.client.models.ReferralProgramReceiverCreditReward
import com.winwinkit.client.models.ReferralProgramReceiverGooglePlayPromoCodeReward
import com.winwinkit.client.models.ReferralProgramReceiverOfferCodeReward
import com.winwinkit.client.models.ReferralProgramReceiverRevenueCatEntitlementReward
import com.winwinkit.client.models.ReferralProgramReceiverRevenueCatOfferingReward

class ReferralProgramReceiverRewardsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ReferralProgramReceiverRewards
        //val modelInstance = ReferralProgramReceiverRewards()

        // to test the property `basic` - The program basic rewards
        should("test basic") {
            // uncomment below to test the property
            //modelInstance.basic shouldBe ("TODO")
        }

        // to test the property `credit` - The program credit rewards
        should("test credit") {
            // uncomment below to test the property
            //modelInstance.credit shouldBe ("TODO")
        }

        // to test the property `offerCode` - The program offer code rewards
        should("test offerCode") {
            // uncomment below to test the property
            //modelInstance.offerCode shouldBe ("TODO")
        }

        // to test the property `googleplayPromoCode` - The program Google Play promo code rewards
        should("test googleplayPromoCode") {
            // uncomment below to test the property
            //modelInstance.googleplayPromoCode shouldBe ("TODO")
        }

        // to test the property `revenuecatEntitlement` - The program RevenueCat entitlement rewards
        should("test revenuecatEntitlement") {
            // uncomment below to test the property
            //modelInstance.revenuecatEntitlement shouldBe ("TODO")
        }

        // to test the property `revenuecatOffering` - The program RevenueCat offering rewards
        should("test revenuecatOffering") {
            // uncomment below to test the property
            //modelInstance.revenuecatOffering shouldBe ("TODO")
        }

    }
}
