/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.winwinkit.client.models.ReferralProgramReceiverCreditRewardIntervalDeactivation

class ReferralProgramReceiverCreditRewardIntervalDeactivationTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ReferralProgramReceiverCreditRewardIntervalDeactivation
        //val modelInstance = ReferralProgramReceiverCreditRewardIntervalDeactivation()

        // to test the property `variant` - The variant of the deactivation configuration
        should("test variant") {
            // uncomment below to test the property
            //modelInstance.variant shouldBe ("TODO")
        }

        // to test the property `duration` - The duration of the deactivation configuration
        should("test duration") {
            // uncomment below to test the property
            //modelInstance.duration shouldBe ("TODO")
        }

        // to test the property `period` - The period of the deactivation configuration
        should("test period") {
            // uncomment below to test the property
            //modelInstance.period shouldBe ("TODO")
        }

    }
}
