/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.winwinkit.client.models.ReferralProgramReceiverCreditRewardActivation

class ReferralProgramReceiverCreditRewardActivationTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ReferralProgramReceiverCreditRewardActivation
        //val modelInstance = ReferralProgramReceiverCreditRewardActivation()

        // to test the property `variant` - The variant of the activation configuration
        should("test variant") {
            // uncomment below to test the property
            //modelInstance.variant shouldBe ("TODO")
        }

    }
}
