/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.winwinkit.client.models.ReferralProgramSenderCreditReward
import com.winwinkit.client.models.CreditReward
import com.winwinkit.client.models.ReferralProgramSenderCreditRewardActivation
import com.winwinkit.client.models.ReferralProgramSenderCreditRewardDeactivation

class ReferralProgramSenderCreditRewardTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ReferralProgramSenderCreditReward
        //val modelInstance = ReferralProgramSenderCreditReward()

        // to test the property `reward` - The reward
        should("test reward") {
            // uncomment below to test the property
            //modelInstance.reward shouldBe ("TODO")
        }

        // to test the property `activation` - The activation configuration
        should("test activation") {
            // uncomment below to test the property
            //modelInstance.activation shouldBe ("TODO")
        }

        // to test the property `deactivation`
        should("test deactivation") {
            // uncomment below to test the property
            //modelInstance.deactivation shouldBe ("TODO")
        }

    }
}
