/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.winwinkit.client.models.ReferralProgramSenderGooglePlayPromoCodeRewardActivation

class ReferralProgramSenderGooglePlayPromoCodeRewardActivationTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ReferralProgramSenderGooglePlayPromoCodeRewardActivation
        //val modelInstance = ReferralProgramSenderGooglePlayPromoCodeRewardActivation()

        // to test the property `variant` - The variant of the activation configuration
        should("test variant") {
            // uncomment below to test the property
            //modelInstance.variant shouldBe ("TODO")
        }

        // to test the property `amount` - The amount of the activation configuration
        should("test amount") {
            // uncomment below to test the property
            //modelInstance.amount shouldBe ("TODO")
        }

        // to test the property `limit` - The limit of the activation configuration
        should("test limit") {
            // uncomment below to test the property
            //modelInstance.limit shouldBe ("TODO")
        }

    }
}
