/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.winwinkit.client.models.UserStats

class UserStatsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UserStats
        //val modelInstance = UserStats()

        // to test the property `claims` - The number of users who have claimed the referral code.
        should("test claims") {
            // uncomment below to test the property
            //modelInstance.claims shouldBe ("TODO")
        }

        // to test the property `conversions` - The number of users who have converted to premium.
        should("test conversions") {
            // uncomment below to test the property
            //modelInstance.conversions shouldBe ("TODO")
        }

        // to test the property `churns` - The number of users who have churned.
        should("test churns") {
            // uncomment below to test the property
            //modelInstance.churns shouldBe ("TODO")
        }

    }
}
