/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.winwinkit.client.models.UserCreateRequest

class UserCreateRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UserCreateRequest
        //val modelInstance = UserCreateRequest()

        // to test the property `appUserId` - The unique identifier of the referral user in your app.
        should("test appUserId") {
            // uncomment below to test the property
            //modelInstance.appUserId shouldBe ("TODO")
        }

        // to test the property `isTrial` - Whether the user is a trial user.
        should("test isTrial") {
            // uncomment below to test the property
            //modelInstance.isTrial shouldBe ("TODO")
        }

        // to test the property `isPremium` - Whether the user is a premium user.
        should("test isPremium") {
            // uncomment below to test the property
            //modelInstance.isPremium shouldBe ("TODO")
        }

        // to test the property `firstSeenAt` - The date when the user was first seen at.
        should("test firstSeenAt") {
            // uncomment below to test the property
            //modelInstance.firstSeenAt shouldBe ("TODO")
        }

        // to test the property `lastSeenAt` - The date when the user was last seen at. Deprecated and will be removed in the future.
        should("test lastSeenAt") {
            // uncomment below to test the property
            //modelInstance.lastSeenAt shouldBe ("TODO")
        }

        // to test the property `metadata` - The metadata of the user.
        should("test metadata") {
            // uncomment below to test the property
            //modelInstance.metadata shouldBe ("TODO")
        }

        // to test the property `stripeCustomerId` - The unique identifier of the user in Stripe.
        should("test stripeCustomerId") {
            // uncomment below to test the property
            //modelInstance.stripeCustomerId shouldBe ("TODO")
        }

    }
}
