/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.winwinkit.client.models.User
import com.winwinkit.client.models.ReferralProgram
import com.winwinkit.client.models.UserClaimCodeEligibility
import com.winwinkit.client.models.UserReferredBy
import com.winwinkit.client.models.UserRewards
import com.winwinkit.client.models.UserStats

class UserTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of User
        //val modelInstance = User()

        // to test the property `appUserId` - The unique identifier of the user in your app.
        should("test appUserId") {
            // uncomment below to test the property
            //modelInstance.appUserId shouldBe ("TODO")
        }

        // to test the property `referralCode` - The referral code of the user.
        should("test referralCode") {
            // uncomment below to test the property
            //modelInstance.referralCode shouldBe ("TODO")
        }

        // to test the property `referralCodeLink` - The referral code link of the user.
        should("test referralCodeLink") {
            // uncomment below to test the property
            //modelInstance.referralCodeLink shouldBe ("TODO")
        }

        // to test the property `isTrial` - Whether the user is a trial user.
        should("test isTrial") {
            // uncomment below to test the property
            //modelInstance.isTrial shouldBe ("TODO")
        }

        // to test the property `isPremium` - Whether the user is a premium user.
        should("test isPremium") {
            // uncomment below to test the property
            //modelInstance.isPremium shouldBe ("TODO")
        }

        // to test the property `firstSeenAt` - The date when the user was first seen at.
        should("test firstSeenAt") {
            // uncomment below to test the property
            //modelInstance.firstSeenAt shouldBe ("TODO")
        }

        // to test the property `lastSeenAt` - The date when the user was last seen at. Deprecated, always returns null and will be removed in the future.
        should("test lastSeenAt") {
            // uncomment below to test the property
            //modelInstance.lastSeenAt shouldBe ("TODO")
        }

        // to test the property `metadata` - The metadata of the user.
        should("test metadata") {
            // uncomment below to test the property
            //modelInstance.metadata shouldBe ("TODO")
        }

        // to test the property `stripeCustomerId` - The unique identifier of the user in Stripe.
        should("test stripeCustomerId") {
            // uncomment below to test the property
            //modelInstance.stripeCustomerId shouldBe ("TODO")
        }

        // to test the property `claimCodeEligibility` - The claim code eligibility of the user.
        should("test claimCodeEligibility") {
            // uncomment below to test the property
            //modelInstance.claimCodeEligibility shouldBe ("TODO")
        }

        // to test the property `referredBy` - The referred by object of the user.
        should("test referredBy") {
            // uncomment below to test the property
            //modelInstance.referredBy shouldBe ("TODO")
        }

        // to test the property `stats` - The stats of the user.
        should("test stats") {
            // uncomment below to test the property
            //modelInstance.stats shouldBe ("TODO")
        }

        // to test the property `rewards` - The rewards of the user.
        should("test rewards") {
            // uncomment below to test the property
            //modelInstance.rewards shouldBe ("TODO")
        }

        // to test the property `referralProgram` - The program of the user.
        should("test referralProgram") {
            // uncomment below to test the property
            //modelInstance.referralProgram shouldBe ("TODO")
        }

    }
}
