/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.winwinkit.client.models.UserClaimCodeRequest

class UserClaimCodeRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UserClaimCodeRequest
        //val modelInstance = UserClaimCodeRequest()

        // to test the property `code` - The code to claim. Can be affiliate, promo or referral code.
        should("test code") {
            // uncomment below to test the property
            //modelInstance.code shouldBe ("TODO")
        }

    }
}
