/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.winwinkit.client.models.UserClaimCodeEligibility

class UserClaimCodeEligibilityTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UserClaimCodeEligibility
        //val modelInstance = UserClaimCodeEligibility()

        // to test the property `eligible` - The claim code eligibility flag.
        should("test eligible") {
            // uncomment below to test the property
            //modelInstance.eligible shouldBe ("TODO")
        }

        // to test the property `eligibleUntil` - The claim code eligibility until date.
        should("test eligibleUntil") {
            // uncomment below to test the property
            //modelInstance.eligibleUntil shouldBe ("TODO")
        }

    }
}
