/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.winwinkit.client.models.UserGooglePlayPromoCodeRewardActive
import com.winwinkit.client.models.GooglePlayPromoCodeReward
import com.winwinkit.client.models.GooglePlayPromoCodeValue

class UserGooglePlayPromoCodeRewardActiveTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UserGooglePlayPromoCodeRewardActive
        //val modelInstance = UserGooglePlayPromoCodeRewardActive()

        // to test the property `reward` - The reward
        should("test reward") {
            // uncomment below to test the property
            //modelInstance.reward shouldBe ("TODO")
        }

        // to test the property ``value`` - The promo code value
        should("test `value`") {
            // uncomment below to test the property
            //modelInstance.`value` shouldBe ("TODO")
        }

        // to test the property `expiresAt` - The expiration date of the reward
        should("test expiresAt") {
            // uncomment below to test the property
            //modelInstance.expiresAt shouldBe ("TODO")
        }

        // to test the property `createdAt` - The created at of the reward
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `updatedAt` - The updated at of the reward
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

    }
}
