/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.winwinkit.client.models.UserAffiliateCode

class UserAffiliateCodeTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UserAffiliateCode
        //val modelInstance = UserAffiliateCode()

        // to test the property `code` - The affiliate code.
        should("test code") {
            // uncomment below to test the property
            //modelInstance.code shouldBe ("TODO")
        }

        // to test the property `codeLink` - The shareable link for the code. Null when the app has turned code links off for the affiliate group.
        should("test codeLink") {
            // uncomment below to test the property
            //modelInstance.codeLink shouldBe ("TODO")
        }

    }
}
