/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.winwinkit.client.models.UserRegisterAppStoreTransactionRequest

class UserRegisterAppStoreTransactionRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UserRegisterAppStoreTransactionRequest
        //val modelInstance = UserRegisterAppStoreTransactionRequest()

        // to test the property `originalTransactionId` - Apple's originalTransactionId from StoreKit.
        should("test originalTransactionId") {
            // uncomment below to test the property
            //modelInstance.originalTransactionId shouldBe ("TODO")
        }

        // to test the property `appAccountToken` - StoreKit 2 appAccountToken UUID.
        should("test appAccountToken") {
            // uncomment below to test the property
            //modelInstance.appAccountToken shouldBe ("TODO")
        }

    }
}
