/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.winwinkit.client.models.UserWithdrawCreditsResult

class UserWithdrawCreditsResultTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UserWithdrawCreditsResult
        //val modelInstance = UserWithdrawCreditsResult()

        // to test the property `creditsAvailableAtStart` - The amount of credits available at the start
        should("test creditsAvailableAtStart") {
            // uncomment below to test the property
            //modelInstance.creditsAvailableAtStart shouldBe ("TODO")
        }

        // to test the property `creditsAvailableAtEnd` - The amount of credits available at the end
        should("test creditsAvailableAtEnd") {
            // uncomment below to test the property
            //modelInstance.creditsAvailableAtEnd shouldBe ("TODO")
        }

        // to test the property `creditsRequestedToWithdraw` - The amount of credits requested to withdraw
        should("test creditsRequestedToWithdraw") {
            // uncomment below to test the property
            //modelInstance.creditsRequestedToWithdraw shouldBe ("TODO")
        }

        // to test the property `creditsWithdrawn` - The amount of credits withdrawn
        should("test creditsWithdrawn") {
            // uncomment below to test the property
            //modelInstance.creditsWithdrawn shouldBe ("TODO")
        }

    }
}
