/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.winwinkit.client.models.UserRewardsExpired
import com.winwinkit.client.models.UserBasicRewardExpired
import com.winwinkit.client.models.UserCreditRewardExpired
import com.winwinkit.client.models.UserGooglePlayPromoCodeRewardExpired
import com.winwinkit.client.models.UserOfferCodeRewardExpired
import com.winwinkit.client.models.UserRevenueCatEntitlementRewardExpired
import com.winwinkit.client.models.UserRevenueCatOfferingRewardExpired

class UserRewardsExpiredTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UserRewardsExpired
        //val modelInstance = UserRewardsExpired()

        // to test the property `basic` - The referral user basic rewards
        should("test basic") {
            // uncomment below to test the property
            //modelInstance.basic shouldBe ("TODO")
        }

        // to test the property `credit` - The referral user credit rewards
        should("test credit") {
            // uncomment below to test the property
            //modelInstance.credit shouldBe ("TODO")
        }

        // to test the property `offerCode` - The referral user offer code rewards
        should("test offerCode") {
            // uncomment below to test the property
            //modelInstance.offerCode shouldBe ("TODO")
        }

        // to test the property `googleplayPromoCode` - The referral user Google Play promo code rewards
        should("test googleplayPromoCode") {
            // uncomment below to test the property
            //modelInstance.googleplayPromoCode shouldBe ("TODO")
        }

        // to test the property `revenuecatEntitlement` - The referral user RevenueCat entitlement rewards
        should("test revenuecatEntitlement") {
            // uncomment below to test the property
            //modelInstance.revenuecatEntitlement shouldBe ("TODO")
        }

        // to test the property `revenuecatOffering` - The referral user RevenueCat offering rewards
        should("test revenuecatOffering") {
            // uncomment below to test the property
            //modelInstance.revenuecatOffering shouldBe ("TODO")
        }

    }
}
