/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.winwinkit.client.models.UserReferredBy

class UserReferredByTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UserReferredBy
        //val modelInstance = UserReferredBy()

        // to test the property `code` - The code claimed by the user. Can be null if the code's entity has been deleted.
        should("test code") {
            // uncomment below to test the property
            //modelInstance.code shouldBe ("TODO")
        }

        // to test the property `type` - The type of the code. Can be one of \"affiliate\", \"promo\", or \"referral\".
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

    }
}
