/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.winwinkit.client.models.UserAffiliateApplyLinkResponseData

class UserAffiliateApplyLinkResponseDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UserAffiliateApplyLinkResponseData
        //val modelInstance = UserAffiliateApplyLinkResponseData()

        // to test the property `link` - The apply link to open, for the requested affiliate group or the app's default group. It carries a short-lived token identifying the user, so the affiliate they become is attributed back to them.
        should("test link") {
            // uncomment below to test the property
            //modelInstance.link shouldBe ("TODO")
        }

    }
}
