/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.winwinkit.client.models.UserWithdrawCreditsResponseData
import com.winwinkit.client.models.User
import com.winwinkit.client.models.UserWithdrawCreditsResult

class UserWithdrawCreditsResponseDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UserWithdrawCreditsResponseData
        //val modelInstance = UserWithdrawCreditsResponseData()

        // to test the property `withdrawResult` - The withdraw result
        should("test withdrawResult") {
            // uncomment below to test the property
            //modelInstance.withdrawResult shouldBe ("TODO")
        }

        // to test the property `user` - The user
        should("test user") {
            // uncomment below to test the property
            //modelInstance.user shouldBe ("TODO")
        }

    }
}
