/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.winwinkit.client.models.UserAffiliateApplyLinkRequest

class UserAffiliateApplyLinkRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UserAffiliateApplyLinkRequest
        //val modelInstance = UserAffiliateApplyLinkRequest()

        // to test the property `groupSlug` - The affiliate group to apply to. Omit to link to the app's default group.
        should("test groupSlug") {
            // uncomment below to test the property
            //modelInstance.groupSlug shouldBe ("TODO")
        }

    }
}
