/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.winwinkit.client.models.UserRewards
import com.winwinkit.client.models.UserRewardsActive
import com.winwinkit.client.models.UserRewardsExpired

class UserRewardsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UserRewards
        //val modelInstance = UserRewards()

        // to test the property `active` - The referral user active rewards
        should("test active") {
            // uncomment below to test the property
            //modelInstance.active shouldBe ("TODO")
        }

        // to test the property `expired` - The referral user expired rewards
        should("test expired") {
            // uncomment below to test the property
            //modelInstance.expired shouldBe ("TODO")
        }

    }
}
