/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.winwinkit.client.models.UserRegisterGooglePlayTransactionRequest

class UserRegisterGooglePlayTransactionRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UserRegisterGooglePlayTransactionRequest
        //val modelInstance = UserRegisterGooglePlayTransactionRequest()

        // to test the property `purchaseToken` - Google Play's purchaseToken from the purchase flow.
        should("test purchaseToken") {
            // uncomment below to test the property
            //modelInstance.purchaseToken shouldBe ("TODO")
        }

        // to test the property `obfuscatedExternalAccountId` - Set in BillingFlowParams.setObfuscatedAccountId() — used for better matching.
        should("test obfuscatedExternalAccountId") {
            // uncomment below to test the property
            //modelInstance.obfuscatedExternalAccountId shouldBe ("TODO")
        }

    }
}
