/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.winwinkit.client.models.UserAffiliate
import com.winwinkit.client.models.UserAffiliateCode
import com.winwinkit.client.models.UserAffiliateStats

class UserAffiliateTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UserAffiliate
        //val modelInstance = UserAffiliate()

        // to test the property `id` - The unique identifier of the affiliate.
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `status` - Where the affiliate stands with this app. `banned` is terminal; `rejected`, `withdrawn`, `archived` and `deactivated` describe affiliates who may apply again.
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `codes` - The codes the affiliate can currently promote, oldest first. Empty until they create one — an approved affiliate with no code yet is a normal state.
        should("test codes") {
            // uncomment below to test the property
            //modelInstance.codes shouldBe ("TODO")
        }

        // to test the property `stats` - The affiliate's totals on this app.
        should("test stats") {
            // uncomment below to test the property
            //modelInstance.stats shouldBe ("TODO")
        }

    }
}
