/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.winwinkit.client.models.UserGrantRewardResponseData
import com.winwinkit.client.models.User
import com.winwinkit.client.models.UserRewardsGranted

class UserGrantRewardResponseDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UserGrantRewardResponseData
        //val modelInstance = UserGrantRewardResponseData()

        // to test the property `rewardsGranted` - The rewards granted to the user.
        should("test rewardsGranted") {
            // uncomment below to test the property
            //modelInstance.rewardsGranted shouldBe ("TODO")
        }

        // to test the property `user` - The updated user.
        should("test user") {
            // uncomment below to test the property
            //modelInstance.user shouldBe ("TODO")
        }

    }
}
