/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.winwinkit.client.models.UserWithdrawCreditsRequest

class UserWithdrawCreditsRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UserWithdrawCreditsRequest
        //val modelInstance = UserWithdrawCreditsRequest()

        // to test the property `key` - The key of the credit reward to withdraw
        should("test key") {
            // uncomment below to test the property
            //modelInstance.key shouldBe ("TODO")
        }

        // to test the property `amount` - The amount of credits to withdraw
        should("test amount") {
            // uncomment below to test the property
            //modelInstance.amount shouldBe ("TODO")
        }

        // to test the property `operationId` - An optional operation id that ensures the same operation won't be performed again
        should("test operationId") {
            // uncomment below to test the property
            //modelInstance.operationId shouldBe ("TODO")
        }

    }
}
