/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.winwinkit.client.models.UserAffiliateStats

class UserAffiliateStatsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UserAffiliateStats
        //val modelInstance = UserAffiliateStats()

        // to test the property `claims` - The number of users who have claimed one of their codes.
        should("test claims") {
            // uncomment below to test the property
            //modelInstance.claims shouldBe ("TODO")
        }

        // to test the property `conversions` - The number of users who have converted to premium.
        should("test conversions") {
            // uncomment below to test the property
            //modelInstance.conversions shouldBe ("TODO")
        }

        // to test the property `earnings` - The commission accrued all-time, in USD cents. Gross and cumulative — not a balance, and not an amount available to withdraw.
        should("test earnings") {
            // uncomment below to test the property
            //modelInstance.earnings shouldBe ("TODO")
        }

    }
}
