/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.winwinkit.client.apis.AnalyticsApi
import com.winwinkit.client.models.AffiliateAnalyticsResponse
import com.winwinkit.client.models.ErrorsResponse

class AnalyticsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AnalyticsApi
        //val apiInstance = AnalyticsApi()

        // to test getAffiliateAnalytics
        should("test getAffiliateAnalytics") {
            // uncomment below to test getAffiliateAnalytics
            //val from : java.time.LocalDate = Thu Jan 01 01:00:00 CET 2026 // java.time.LocalDate | The first day of the period, inclusive, as YYYY-MM-DD (UTC).
            //val to : java.time.LocalDate = Tue Mar 31 02:00:00 CEST 2026 // java.time.LocalDate | The last day of the period, inclusive, as YYYY-MM-DD (UTC). Must not be before `from`, and the period must be at most 90 days long.
            //val xApiKey : kotlin.String = xApiKey_example // kotlin.String | The secret API key.
            //val limit : java.math.BigDecimal = 100 // java.math.BigDecimal | How many affiliates to return, from 10 to 100.
            //val offset : java.math.BigDecimal = 0 // java.math.BigDecimal | How many affiliates to skip before the page.
            //val result : AffiliateAnalyticsResponse = apiInstance.getAffiliateAnalytics(from, to, xApiKey, limit, offset)
            //result shouldBe ("TODO")
        }

    }
}
