/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.winwinkit.client.apis.AppStoreApi
import com.winwinkit.client.models.ErrorsResponse
import com.winwinkit.client.models.OfferCodeResponse

class AppStoreApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AppStoreApi
        //val apiInstance = AppStoreApi()

        // to test getOfferCode
        should("test getOfferCode") {
            // uncomment below to test getOfferCode
            //val offerCodeId : kotlin.String = offerCodeId_example // kotlin.String | The offer code id to retrieve.
            //val xApiKey : kotlin.String = xApiKey_example // kotlin.String | The API key to authenticate with.
            //val result : OfferCodeResponse = apiInstance.getOfferCode(offerCodeId, xApiKey)
            //result shouldBe ("TODO")
        }

    }
}
