/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.winwinkit.client.apis.ClaimActionsApi
import com.winwinkit.client.models.ErrorsResponse
import com.winwinkit.client.models.UserClaimCodeRequest
import com.winwinkit.client.models.UserClaimCodeResponse

class ClaimActionsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ClaimActionsApi
        //val apiInstance = ClaimActionsApi()

        // to test claimCode
        should("test claimCode") {
            // uncomment below to test claimCode
            //val appUserId : kotlin.String = appUserId_example // kotlin.String | The app user id of the user to claim the code for.
            //val xApiKey : kotlin.String = xApiKey_example // kotlin.String | The API key to authenticate with.
            //val userClaimCodeRequest : UserClaimCodeRequest =  // UserClaimCodeRequest | 
            //val result : UserClaimCodeResponse = apiInstance.claimCode(appUserId, xApiKey, userClaimCodeRequest)
            //result shouldBe ("TODO")
        }

    }
}
