/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.winwinkit.client.apis.CodesApi
import com.winwinkit.client.models.CodeResponse
import com.winwinkit.client.models.ErrorsResponse

class CodesApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CodesApi
        //val apiInstance = CodesApi()

        // to test getCode
        should("test getCode") {
            // uncomment below to test getCode
            //val code : kotlin.String = code_example // kotlin.String | The code to look up.
            //val xApiKey : kotlin.String = xApiKey_example // kotlin.String | The API key to authenticate with.
            //val result : CodeResponse = apiInstance.getCode(code, xApiKey)
            //result shouldBe ("TODO")
        }

    }
}
