/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.winwinkit.client.apis.RewardsActionsApi
import com.winwinkit.client.models.ErrorsResponse
import com.winwinkit.client.models.UserGrantRewardRequest
import com.winwinkit.client.models.UserGrantRewardResponse
import com.winwinkit.client.models.UserWithdrawCreditsRequest
import com.winwinkit.client.models.UserWithdrawCreditsResponse

class RewardsActionsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RewardsActionsApi
        //val apiInstance = RewardsActionsApi()

        // to test grantReward
        should("test grantReward") {
            // uncomment below to test grantReward
            //val appUserId : kotlin.String = appUserId_example // kotlin.String | The app user id of the user to grant a reward to.
            //val xApiKey : kotlin.String = xApiKey_example // kotlin.String | The secret API key.
            //val userGrantRewardRequest : UserGrantRewardRequest =  // UserGrantRewardRequest | 
            //val result : UserGrantRewardResponse = apiInstance.grantReward(appUserId, xApiKey, userGrantRewardRequest)
            //result shouldBe ("TODO")
        }

        // to test withdrawCredits
        should("test withdrawCredits") {
            // uncomment below to test withdrawCredits
            //val appUserId : kotlin.String = appUserId_example // kotlin.String | The app user id of the user to withdraw credits from.
            //val xApiKey : kotlin.String = xApiKey_example // kotlin.String | The API key to authenticate with.
            //val userWithdrawCreditsRequest : UserWithdrawCreditsRequest =  // UserWithdrawCreditsRequest | 
            //val result : UserWithdrawCreditsResponse = apiInstance.withdrawCredits(appUserId, xApiKey, userWithdrawCreditsRequest)
            //result shouldBe ("TODO")
        }

    }
}
