/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.winwinkit.client.apis.UsersApi
import com.winwinkit.client.models.ErrorsResponse
import com.winwinkit.client.models.UserCreateRequest
import com.winwinkit.client.models.UserResponse

class UsersApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UsersApi
        //val apiInstance = UsersApi()

        // to test createOrUpdateUser
        should("test createOrUpdateUser") {
            // uncomment below to test createOrUpdateUser
            //val xApiKey : kotlin.String = xApiKey_example // kotlin.String | The API key to authenticate with.
            //val userCreateRequest : UserCreateRequest =  // UserCreateRequest | 
            //val result : UserResponse = apiInstance.createOrUpdateUser(xApiKey, userCreateRequest)
            //result shouldBe ("TODO")
        }

        // to test getUser
        should("test getUser") {
            // uncomment below to test getUser
            //val appUserId : kotlin.String = appUserId_example // kotlin.String | The app user id of the user to retrieve.
            //val xApiKey : kotlin.String = xApiKey_example // kotlin.String | The API key to authenticate with.
            //val result : UserResponse = apiInstance.getUser(appUserId, xApiKey)
            //result shouldBe ("TODO")
        }

    }
}
