/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import com.winwinkit.client.models.AffiliateAnalyticsMetrics

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id The affiliate id
 * @param name The affiliate name
 * @param acceptedAt When the affiliate joined the project
 * @param status The affiliate current standing with the project. Not always `approved`: an affiliate is reported for what they did in the period, so one since banned or deactivated still appears alongside the metrics they earned.
 * @param totals The affiliate's totals over the period
 */
@JsonClass(generateAdapter = true)

data class AffiliateAnalyticsEntry (

    /* The affiliate id */
    @Json(name = "id")
    val id: kotlin.String,

    /* The affiliate name */
    @Json(name = "name")
    val name: kotlin.String,

    /* When the affiliate joined the project */
    @Json(name = "accepted_at")
    val acceptedAt: java.time.OffsetDateTime,

    /* The affiliate current standing with the project. Not always `approved`: an affiliate is reported for what they did in the period, so one since banned or deactivated still appears alongside the metrics they earned. */
    @Json(name = "status")
    val status: AffiliateAnalyticsEntry.Status,

    /* The affiliate's totals over the period */
    @Json(name = "totals")
    val totals: AffiliateAnalyticsMetrics

) {

    /**
     * The affiliate current standing with the project. Not always `approved`: an affiliate is reported for what they did in the period, so one since banned or deactivated still appears alongside the metrics they earned.
     *
     * Values: pending,withdrawn,approved,rejected,archived,deactivated,banned
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "pending") pending("pending"),
        @Json(name = "withdrawn") withdrawn("withdrawn"),
        @Json(name = "approved") approved("approved"),
        @Json(name = "rejected") rejected("rejected"),
        @Json(name = "archived") archived("archived"),
        @Json(name = "deactivated") deactivated("deactivated"),
        @Json(name = "banned") banned("banned");
    }

}

