/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param claims The number of times the affiliate's codes were claimed
 * @param conversions The number of claims that converted into a purchase
 * @param revenue The revenue attributed to the affiliate, in USD cents
 * @param earnings The commission owed to the affiliate on that revenue, in USD cents
 */
@JsonClass(generateAdapter = true)

data class AffiliateAnalyticsMetrics (

    /* The number of times the affiliate's codes were claimed */
    @Json(name = "claims")
    val claims: java.math.BigDecimal,

    /* The number of claims that converted into a purchase */
    @Json(name = "conversions")
    val conversions: java.math.BigDecimal,

    /* The revenue attributed to the affiliate, in USD cents */
    @Json(name = "revenue")
    val revenue: java.math.BigDecimal,

    /* The commission owed to the affiliate on that revenue, in USD cents */
    @Json(name = "earnings")
    val earnings: java.math.BigDecimal

) {


}

