/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type The platform type
 * @param handle The public handle/username on the platform
 * @param verified Whether ownership of the platform has been verified
 */
@JsonClass(generateAdapter = true)

data class AffiliatePlatform (

    /* The platform type */
    @Json(name = "type")
    val type: AffiliatePlatform.Type,

    /* The public handle/username on the platform */
    @Json(name = "handle")
    val handle: kotlin.String,

    /* Whether ownership of the platform has been verified */
    @Json(name = "verified")
    val verified: kotlin.Boolean

) {

    /**
     * The platform type
     *
     * Values: instagram,tiktok,youtube,twitter,website
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "instagram") instagram("instagram"),
        @Json(name = "tiktok") tiktok("tiktok"),
        @Json(name = "youtube") youtube("youtube"),
        @Json(name = "twitter") twitter("twitter"),
        @Json(name = "website") website("website");
    }

}

