/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import com.winwinkit.client.models.AffiliateAnalyticsEntry
import com.winwinkit.client.models.AffiliateAnalyticsMetrics
import com.winwinkit.client.models.Pagination

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param from The first day of the period, inclusive
 * @param to The last day of the period, inclusive
 * @param totals The totals across every affiliate in the period, not just this page
 * @param affiliates The page of affiliates, oldest joiner first. Affiliates with no activity in the period are omitted.
 * @param pagination Where this page sits within the affiliates that matched
 */
@JsonClass(generateAdapter = true)

data class AffiliateAnalytics (

    /* The first day of the period, inclusive */
    @Json(name = "from")
    val from: kotlin.String,

    /* The last day of the period, inclusive */
    @Json(name = "to")
    val to: kotlin.String,

    /* The totals across every affiliate in the period, not just this page */
    @Json(name = "totals")
    val totals: AffiliateAnalyticsMetrics,

    /* The page of affiliates, oldest joiner first. Affiliates with no activity in the period are omitted. */
    @Json(name = "affiliates")
    val affiliates: kotlin.collections.List<AffiliateAnalyticsEntry>,

    /* Where this page sits within the affiliates that matched */
    @Json(name = "pagination")
    val pagination: Pagination

) {


}

