/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import com.winwinkit.client.models.AppStorePrice

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The offer code
 *
 * @param id The offer code id.
 * @param name The offer code name.
 * @param customerEligibilities The offer code customer eligibilities.
 * @param offerEligibility The offer code offer eligibility.
 * @param duration The offer code duration.
 * @param offerMode The offer code offer mode.
 * @param numberOfPeriods The offer code number of periods.
 * @param prices The offer code prices.
 */


data class AppStoreOfferCode (

    /* The offer code id. */
    @Json(name = "id")
    val id: kotlin.String,

    /* The offer code name. */
    @Json(name = "name")
    val name: kotlin.String,

    /* The offer code customer eligibilities. */
    @Json(name = "customer_eligibilities")
    val customerEligibilities: kotlin.collections.List<kotlin.String>,

    /* The offer code offer eligibility. */
    @Json(name = "offer_eligibility")
    val offerEligibility: AppStoreOfferCode.OfferEligibility,

    /* The offer code duration. */
    @Json(name = "duration")
    val duration: AppStoreOfferCode.Duration,

    /* The offer code offer mode. */
    @Json(name = "offer_mode")
    val offerMode: AppStoreOfferCode.OfferMode,

    /* The offer code number of periods. */
    @Json(name = "number_of_periods")
    val numberOfPeriods: kotlin.Int,

    /* The offer code prices. */
    @Json(name = "prices")
    val prices: kotlin.collections.List<AppStorePrice>?

) {

    /**
     * The offer code offer eligibility.
     *
     * Values: STACK_WITH_INTRO_OFFERS,REPLACE_INTRO_OFFERS
     */
    @JsonClass(generateAdapter = false)
    enum class OfferEligibility(val value: kotlin.String) {
        @Json(name = "STACK_WITH_INTRO_OFFERS") STACK_WITH_INTRO_OFFERS("STACK_WITH_INTRO_OFFERS"),
        @Json(name = "REPLACE_INTRO_OFFERS") REPLACE_INTRO_OFFERS("REPLACE_INTRO_OFFERS");
    }
    /**
     * The offer code duration.
     *
     * Values: THREE_DAYS,ONE_WEEK,TWO_WEEKS,ONE_MONTH,TWO_MONTHS,THREE_MONTHS,SIX_MONTHS,ONE_YEAR
     */
    @JsonClass(generateAdapter = false)
    enum class Duration(val value: kotlin.String) {
        @Json(name = "THREE_DAYS") THREE_DAYS("THREE_DAYS"),
        @Json(name = "ONE_WEEK") ONE_WEEK("ONE_WEEK"),
        @Json(name = "TWO_WEEKS") TWO_WEEKS("TWO_WEEKS"),
        @Json(name = "ONE_MONTH") ONE_MONTH("ONE_MONTH"),
        @Json(name = "TWO_MONTHS") TWO_MONTHS("TWO_MONTHS"),
        @Json(name = "THREE_MONTHS") THREE_MONTHS("THREE_MONTHS"),
        @Json(name = "SIX_MONTHS") SIX_MONTHS("SIX_MONTHS"),
        @Json(name = "ONE_YEAR") ONE_YEAR("ONE_YEAR");
    }
    /**
     * The offer code offer mode.
     *
     * Values: PAY_AS_YOU_GO,PAY_UP_FRONT,FREE_TRIAL
     */
    @JsonClass(generateAdapter = false)
    enum class OfferMode(val value: kotlin.String) {
        @Json(name = "PAY_AS_YOU_GO") PAY_AS_YOU_GO("PAY_AS_YOU_GO"),
        @Json(name = "PAY_UP_FRONT") PAY_UP_FRONT("PAY_UP_FRONT"),
        @Json(name = "FREE_TRIAL") FREE_TRIAL("FREE_TRIAL");
    }

}

