/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The price
 *
 * @param territory The price territory.
 * @param price The price amount.
 * @param currency The price currency.
 */


data class AppStorePrice (

    /* The price territory. */
    @Json(name = "territory")
    val territory: kotlin.String,

    /* The price amount. */
    @Json(name = "price")
    val price: kotlin.String,

    /* The price currency. */
    @Json(name = "currency")
    val currency: kotlin.String

) {


}

