/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import com.winwinkit.client.models.AppStorePrice

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The subscription on the App Store
 *
 * @param id The subscription id.
 * @param productId The product id.
 * @param name The subscription name.
 * @param subscriptionPeriod The subscription period.
 * @param prices The prices of the subscription.
 */


data class AppStoreSubscription (

    /* The subscription id. */
    @Json(name = "id")
    val id: kotlin.String,

    /* The product id. */
    @Json(name = "product_id")
    val productId: kotlin.String,

    /* The subscription name. */
    @Json(name = "name")
    val name: kotlin.String,

    /* The subscription period. */
    @Json(name = "subscription_period")
    val subscriptionPeriod: AppStoreSubscription.SubscriptionPeriod,

    /* The prices of the subscription. */
    @Json(name = "prices")
    val prices: kotlin.collections.List<AppStorePrice>

) {

    /**
     * The subscription period.
     *
     * Values: ONE_WEEK,ONE_MONTH,TWO_MONTHS,THREE_MONTHS,SIX_MONTHS,ONE_YEAR
     */
    @JsonClass(generateAdapter = false)
    enum class SubscriptionPeriod(val value: kotlin.String) {
        @Json(name = "ONE_WEEK") ONE_WEEK("ONE_WEEK"),
        @Json(name = "ONE_MONTH") ONE_MONTH("ONE_MONTH"),
        @Json(name = "TWO_MONTHS") TWO_MONTHS("TWO_MONTHS"),
        @Json(name = "THREE_MONTHS") THREE_MONTHS("THREE_MONTHS"),
        @Json(name = "SIX_MONTHS") SIX_MONTHS("SIX_MONTHS"),
        @Json(name = "ONE_YEAR") ONE_YEAR("ONE_YEAR");
    }

}

