/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import com.winwinkit.client.models.AffiliatePlatform

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name The affiliate name
 * @param logoUrl The affiliate logo url
 * @param platforms The affiliate social platforms
 */
@JsonClass(generateAdapter = true)

data class CodeAffiliate (

    /* The affiliate name */
    @Json(name = "name")
    val name: kotlin.String,

    /* The affiliate logo url */
    @Json(name = "logo_url")
    val logoUrl: kotlin.String?,

    /* The affiliate social platforms */
    @Json(name = "platforms")
    val platforms: kotlin.collections.List<AffiliatePlatform>

) {


}

