/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import com.winwinkit.client.models.AffiliatePlatform
import com.winwinkit.client.models.CodeAffiliate
import com.winwinkit.client.models.CodePromoCode
import com.winwinkit.client.models.CodeReferralUser

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The type-specific entity: the affiliate, the promo code, or the referral code owner.
 *
 * @param name The affiliate name
 * @param logoUrl The affiliate logo url
 * @param platforms The affiliate social platforms
 * @param limit The maximum number of times the code can be claimed (0 = unlimited)
 * @param appUserId The app user id of the referral code owner
 */
@JsonClass(generateAdapter = true)

data class CodeEntity (

    /* The affiliate name */
    @Json(name = "name")
    val name: kotlin.String,

    /* The affiliate logo url */
    @Json(name = "logo_url")
    val logoUrl: kotlin.String?,

    /* The affiliate social platforms */
    @Json(name = "platforms")
    val platforms: kotlin.collections.List<AffiliatePlatform>,

    /* The maximum number of times the code can be claimed (0 = unlimited) */
    @Json(name = "limit")
    val limit: kotlin.Int,

    /* The app user id of the referral code owner */
    @Json(name = "app_user_id")
    val appUserId: kotlin.String

) {


}

