/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import com.winwinkit.client.models.CodeEntity
import com.winwinkit.client.models.ReceiverRewards

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type The resolved code type
 * @param code The code
 * @param isActive Whether the code is active and can be claimed
 * @param entity 
 * @param rewards The rewards granted to the user claiming the code
 */
@JsonClass(generateAdapter = true)

data class Code (

    /* The resolved code type */
    @Json(name = "type")
    val type: Code.Type,

    /* The code */
    @Json(name = "code")
    val code: kotlin.String,

    /* Whether the code is active and can be claimed */
    @Json(name = "is_active")
    val isActive: kotlin.Boolean,

    @Json(name = "entity")
    val entity: CodeEntity,

    /* The rewards granted to the user claiming the code */
    @Json(name = "rewards")
    val rewards: ReceiverRewards

) {

    /**
     * The resolved code type
     *
     * Values: affiliate,promo,referral
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "affiliate") affiliate("affiliate"),
        @Json(name = "promo") promo("promo"),
        @Json(name = "referral") referral("referral");
    }

}

