/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param appUserId The app user id of the referral code owner
 */
@JsonClass(generateAdapter = true)

data class CodeReferralUser (

    /* The app user id of the referral code owner */
    @Json(name = "app_user_id")
    val appUserId: kotlin.String

) {


}

