/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param limit The maximum number of times the code can be claimed (0 = unlimited)
 */
@JsonClass(generateAdapter = true)

data class CodePromoCode (

    /* The maximum number of times the code can be claimed (0 = unlimited) */
    @Json(name = "limit")
    val limit: kotlin.Int

) {


}

