/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import com.winwinkit.client.models.ErrorObject

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Errors Response
 *
 * @param errors 
 */


data class ErrorsResponse (

    @Json(name = "errors")
    val errors: kotlin.collections.List<ErrorObject>

) {


}

