/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Error Object
 *
 * @param code 
 * @param status 
 * @param message 
 * @param source 
 */


data class ErrorObject (

    @Json(name = "code")
    val code: kotlin.String,

    @Json(name = "status")
    val status: kotlin.Int,

    @Json(name = "message")
    val message: kotlin.String,

    @Json(name = "source")
    val source: kotlin.String?

) {


}

