/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param `value` The offer code value
 * @param link The offer code redeem link
 * @param expiresAt The offer code value expiration date
 */


data class OfferCodeValue (

    /* The offer code value */
    @Json(name = "value")
    val `value`: kotlin.String,

    /* The offer code redeem link */
    @Json(name = "link")
    val link: kotlin.String,

    /* The offer code value expiration date */
    @Json(name = "expires_at")
    val expiresAt: java.time.OffsetDateTime

) {


}

