/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import com.winwinkit.client.models.AppStoreOfferCode
import com.winwinkit.client.models.AppStoreSubscription

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param offerCode The offer code
 * @param subscription The subscription
 */


data class OfferCodeResponseData (

    /* The offer code */
    @Json(name = "offer_code")
    val offerCode: AppStoreOfferCode,

    /* The subscription */
    @Json(name = "subscription")
    val subscription: AppStoreSubscription

) {


}

