/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param limit How many results were requested
 * @param offset How many results were skipped before this page
 * @param total How many results matched in total, across every page
 * @param hasMore Whether another page follows this one
 */
@JsonClass(generateAdapter = true)

data class Pagination (

    /* How many results were requested */
    @Json(name = "limit")
    val limit: java.math.BigDecimal,

    /* How many results were skipped before this page */
    @Json(name = "offset")
    val offset: java.math.BigDecimal,

    /* How many results matched in total, across every page */
    @Json(name = "total")
    val total: java.math.BigDecimal,

    /* Whether another page follows this one */
    @Json(name = "has_more")
    val hasMore: kotlin.Boolean

) {


}

