/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param variant When the reward is activated for the receiver
 */
@JsonClass(generateAdapter = true)

data class ReceiverRewardClaimActivation (

    /* When the reward is activated for the receiver */
    @Json(name = "variant")
    val variant: ReceiverRewardClaimActivation.Variant

) {

    /**
     * When the reward is activated for the receiver
     *
     * Values: claim
     */
    @JsonClass(generateAdapter = false)
    enum class Variant(val value: kotlin.String) {
        @Json(name = "claim") claim("claim");
    }

}

