/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import com.winwinkit.client.models.ReceiverRewardIntervalDeactivation
import com.winwinkit.client.models.ReceiverRewardNeverDeactivation

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * When the reward deactivates for the receiver
 *
 * @param variant The reward deactivates after a fixed interval
 * @param duration The duration of the interval
 * @param period The period of the interval
 */
@JsonClass(generateAdapter = true)

data class ReceiverBasicRewardDeactivation (

    /* The reward deactivates after a fixed interval */
    @Json(name = "variant")
    val variant: ReceiverBasicRewardDeactivation.Variant,

    /* The duration of the interval */
    @Json(name = "duration")
    val duration: kotlin.Int,

    /* The period of the interval */
    @Json(name = "period")
    val period: ReceiverBasicRewardDeactivation.Period

) {

    /**
     * The reward deactivates after a fixed interval
     *
     * Values: interval
     */
    @JsonClass(generateAdapter = false)
    enum class Variant(val value: kotlin.String) {
        @Json(name = "interval") interval("interval");
    }
    /**
     * The period of the interval
     *
     * Values: days,months,years
     */
    @JsonClass(generateAdapter = false)
    enum class Period(val value: kotlin.String) {
        @Json(name = "days") days("days"),
        @Json(name = "months") months("months"),
        @Json(name = "years") years("years");
    }

}

