/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import com.winwinkit.client.models.ReceiverBasicReward
import com.winwinkit.client.models.ReceiverCreditReward
import com.winwinkit.client.models.ReceiverGooglePlayPromoCodeReward
import com.winwinkit.client.models.ReceiverOfferCodeReward
import com.winwinkit.client.models.ReceiverRevenueCatEntitlementReward
import com.winwinkit.client.models.ReceiverRevenueCatOfferingReward

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param basic The basic rewards
 * @param credit The credit rewards
 * @param offerCode The offer code rewards
 * @param googleplayPromoCode The Google Play promo code rewards
 * @param revenuecatEntitlement The RevenueCat entitlement rewards
 * @param revenuecatOffering The RevenueCat offering rewards
 */
@JsonClass(generateAdapter = true)

data class ReceiverRewards (

    /* The basic rewards */
    @Json(name = "basic")
    val basic: kotlin.collections.List<ReceiverBasicReward>,

    /* The credit rewards */
    @Json(name = "credit")
    val credit: kotlin.collections.List<ReceiverCreditReward>,

    /* The offer code rewards */
    @Json(name = "offer_code")
    val offerCode: kotlin.collections.List<ReceiverOfferCodeReward>,

    /* The Google Play promo code rewards */
    @Json(name = "googleplay_promo_code")
    val googleplayPromoCode: kotlin.collections.List<ReceiverGooglePlayPromoCodeReward>,

    /* The RevenueCat entitlement rewards */
    @Json(name = "revenuecat_entitlement")
    val revenuecatEntitlement: kotlin.collections.List<ReceiverRevenueCatEntitlementReward>,

    /* The RevenueCat offering rewards */
    @Json(name = "revenuecat_offering")
    val revenuecatOffering: kotlin.collections.List<ReceiverRevenueCatOfferingReward>

) {


}

