/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import com.winwinkit.client.models.GooglePlayPromoCodeReward
import com.winwinkit.client.models.ReceiverBasicRewardDeactivation
import com.winwinkit.client.models.ReceiverRewardClaimActivation

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param reward The reward
 * @param activation 
 * @param deactivation 
 */
@JsonClass(generateAdapter = true)

data class ReceiverGooglePlayPromoCodeReward (

    /* The reward */
    @Json(name = "reward")
    val reward: GooglePlayPromoCodeReward,

    @Json(name = "activation")
    val activation: ReceiverRewardClaimActivation,

    @Json(name = "deactivation")
    val deactivation: ReceiverBasicRewardDeactivation

) {


}

