/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param variant The reward never deactivates
 */
@JsonClass(generateAdapter = true)

data class ReceiverRewardNeverDeactivation (

    /* The reward never deactivates */
    @Json(name = "variant")
    val variant: ReceiverRewardNeverDeactivation.Variant

) {

    /**
     * The reward never deactivates
     *
     * Values: never
     */
    @JsonClass(generateAdapter = false)
    enum class Variant(val value: kotlin.String) {
        @Json(name = "never") never("never");
    }

}

