/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import com.winwinkit.client.models.ReferralProgramRewards

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id The program id
 * @param name The program name
 * @param description The program description
 * @param metadata The program metadata
 * @param distributionPercentage The program distribution percentage
 * @param limit The program limit
 * @param rewards The program rewards
 * @param createdAt The program created at
 * @param updatedAt The program updated at
 */


data class ReferralProgram (

    /* The program id */
    @Json(name = "id")
    val id: kotlin.String,

    /* The program name */
    @Json(name = "name")
    val name: kotlin.String,

    /* The program description */
    @Json(name = "description")
    val description: kotlin.String?,

    /* The program metadata */
    @Json(name = "metadata")
    val metadata: kotlin.Any?,

    /* The program distribution percentage */
    @Json(name = "distribution_percentage")
    val distributionPercentage: kotlin.Int,

    /* The program limit */
    @Json(name = "limit")
    val limit: kotlin.Int,

    /* The program rewards */
    @Json(name = "rewards")
    val rewards: ReferralProgramRewards,

    /* The program created at */
    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime,

    /* The program updated at */
    @Json(name = "updated_at")
    val updatedAt: java.time.OffsetDateTime?

) {


}

