/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param variant The variant of the activation configuration
 * @param amount The amount of the activation configuration
 */


data class ReferralProgramSenderRevenueCatOfferingRewardActivation (

    /* The variant of the activation configuration */
    @Json(name = "variant")
    val variant: ReferralProgramSenderRevenueCatOfferingRewardActivation.Variant,

    /* The amount of the activation configuration */
    @Json(name = "amount")
    val amount: kotlin.Int

) {

    /**
     * The variant of the activation configuration
     *
     * Values: claim,conversion
     */
    @JsonClass(generateAdapter = false)
    enum class Variant(val value: kotlin.String) {
        @Json(name = "claim") claim("claim"),
        @Json(name = "conversion") conversion("conversion");
    }

}

