/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import com.winwinkit.client.models.ReferralProgramReceiverBasicReward
import com.winwinkit.client.models.ReferralProgramReceiverCreditReward
import com.winwinkit.client.models.ReferralProgramReceiverGooglePlayPromoCodeReward
import com.winwinkit.client.models.ReferralProgramReceiverOfferCodeReward
import com.winwinkit.client.models.ReferralProgramReceiverRevenueCatEntitlementReward
import com.winwinkit.client.models.ReferralProgramReceiverRevenueCatOfferingReward

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param basic The program basic rewards
 * @param credit The program credit rewards
 * @param offerCode The program offer code rewards
 * @param googleplayPromoCode The program Google Play promo code rewards
 * @param revenuecatEntitlement The program RevenueCat entitlement rewards
 * @param revenuecatOffering The program RevenueCat offering rewards
 */


data class ReferralProgramReceiverRewards (

    /* The program basic rewards */
    @Json(name = "basic")
    val basic: kotlin.collections.List<ReferralProgramReceiverBasicReward>,

    /* The program credit rewards */
    @Json(name = "credit")
    val credit: kotlin.collections.List<ReferralProgramReceiverCreditReward>,

    /* The program offer code rewards */
    @Json(name = "offer_code")
    val offerCode: kotlin.collections.List<ReferralProgramReceiverOfferCodeReward>,

    /* The program Google Play promo code rewards */
    @Json(name = "googleplay_promo_code")
    val googleplayPromoCode: kotlin.collections.List<ReferralProgramReceiverGooglePlayPromoCodeReward>,

    /* The program RevenueCat entitlement rewards */
    @Json(name = "revenuecat_entitlement")
    val revenuecatEntitlement: kotlin.collections.List<ReferralProgramReceiverRevenueCatEntitlementReward>,

    /* The program RevenueCat offering rewards */
    @Json(name = "revenuecat_offering")
    val revenuecatOffering: kotlin.collections.List<ReferralProgramReceiverRevenueCatOfferingReward>

) {


}

