/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import com.winwinkit.client.models.ReferralProgramSenderRevenueCatOfferingRewardIntervalDeactivation
import com.winwinkit.client.models.ReferralProgramSenderRevenueCatOfferingRewardNeverDeactivation

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The deactivation configuration
 *
 * @param variant The variant of the deactivation configuration
 * @param duration The duration of the deactivation configuration
 * @param period The period of the deactivation configuration
 */


data class ReferralProgramSenderRevenueCatOfferingRewardDeactivation (

    /* The variant of the deactivation configuration */
    @Json(name = "variant")
    val variant: ReferralProgramSenderRevenueCatOfferingRewardDeactivation.Variant,

    /* The duration of the deactivation configuration */
    @Json(name = "duration")
    val duration: kotlin.Int,

    /* The period of the deactivation configuration */
    @Json(name = "period")
    val period: ReferralProgramSenderRevenueCatOfferingRewardDeactivation.Period

) {

    /**
     * The variant of the deactivation configuration
     *
     * Values: interval
     */
    @JsonClass(generateAdapter = false)
    enum class Variant(val value: kotlin.String) {
        @Json(name = "interval") interval("interval");
    }
    /**
     * The period of the deactivation configuration
     *
     * Values: days,months,years
     */
    @JsonClass(generateAdapter = false)
    enum class Period(val value: kotlin.String) {
        @Json(name = "days") days("days"),
        @Json(name = "months") months("months"),
        @Json(name = "years") years("years");
    }

}

