/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param variant The variant of the deactivation configuration
 */


data class ReferralProgramReceiverGooglePlayPromoCodeRewardNeverDeactivation (

    /* The variant of the deactivation configuration */
    @Json(name = "variant")
    val variant: ReferralProgramReceiverGooglePlayPromoCodeRewardNeverDeactivation.Variant

) {

    /**
     * The variant of the deactivation configuration
     *
     * Values: never
     */
    @JsonClass(generateAdapter = false)
    enum class Variant(val value: kotlin.String) {
        @Json(name = "never") never("never");
    }

}

