/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import com.winwinkit.client.models.CreditReward
import com.winwinkit.client.models.ReferralProgramReceiverCreditRewardActivation
import com.winwinkit.client.models.ReferralProgramReceiverCreditRewardDeactivation

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param reward The reward
 * @param activation The activation configuration
 * @param deactivation 
 */


data class ReferralProgramReceiverCreditReward (

    /* The reward */
    @Json(name = "reward")
    val reward: CreditReward,

    /* The activation configuration */
    @Json(name = "activation")
    val activation: ReferralProgramReceiverCreditRewardActivation,

    @Json(name = "deactivation")
    val deactivation: ReferralProgramReceiverCreditRewardDeactivation

) {


}

