/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import com.winwinkit.client.models.GooglePlayPromoCodeReward
import com.winwinkit.client.models.ReferralProgramSenderGooglePlayPromoCodeRewardActivation
import com.winwinkit.client.models.ReferralProgramSenderGooglePlayPromoCodeRewardDeactivation

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param reward The reward
 * @param activation The activation configuration
 * @param deactivation 
 */


data class ReferralProgramSenderGooglePlayPromoCodeReward (

    /* The reward */
    @Json(name = "reward")
    val reward: GooglePlayPromoCodeReward,

    /* The activation configuration */
    @Json(name = "activation")
    val activation: ReferralProgramSenderGooglePlayPromoCodeRewardActivation,

    @Json(name = "deactivation")
    val deactivation: ReferralProgramSenderGooglePlayPromoCodeRewardDeactivation

) {


}

