/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import com.winwinkit.client.models.ReferralProgramReceiverRewards
import com.winwinkit.client.models.ReferralProgramSenderRewards

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param sender The program sender rewards
 * @param `receiver` The program receiver rewards
 */


data class ReferralProgramRewards (

    /* The program sender rewards */
    @Json(name = "sender")
    val sender: ReferralProgramSenderRewards,

    /* The program receiver rewards */
    @Json(name = "receiver")
    val `receiver`: ReferralProgramReceiverRewards

) {


}

