/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param key The key of the reward
 * @param entitlementId The entitlement ID of the reward
 * @param entitlementKey The entitlement key of the reward
 * @param name The name of the reward
 * @param description The description of the reward
 * @param metadata The metadata of the reward
 * @param createdAt The created at of the reward
 * @param updatedAt The updated at of the reward
 */


data class RevenueCatEntitlementReward (

    /* The key of the reward */
    @Json(name = "key")
    val key: kotlin.String,

    /* The entitlement ID of the reward */
    @Json(name = "entitlement_id")
    val entitlementId: kotlin.String,

    /* The entitlement key of the reward */
    @Json(name = "entitlement_key")
    val entitlementKey: kotlin.String,

    /* The name of the reward */
    @Json(name = "name")
    val name: kotlin.String,

    /* The description of the reward */
    @Json(name = "description")
    val description: kotlin.String?,

    /* The metadata of the reward */
    @Json(name = "metadata")
    val metadata: kotlin.Any?,

    /* The created at of the reward */
    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime,

    /* The updated at of the reward */
    @Json(name = "updated_at")
    val updatedAt: java.time.OffsetDateTime?

) {


}

