/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import com.winwinkit.client.models.CreditReward

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param reward The reward
 * @param credits The amount of the reward
 * @param expiresAt The expiration date of the reward
 * @param createdAt The created at of the reward
 * @param updatedAt The updated at of the reward
 */


data class UserCreditRewardActive (

    /* The reward */
    @Json(name = "reward")
    val reward: CreditReward,

    /* The amount of the reward */
    @Json(name = "credits")
    val credits: kotlin.Int,

    /* The expiration date of the reward */
    @Json(name = "expires_at")
    val expiresAt: java.time.OffsetDateTime?,

    /* The created at of the reward */
    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime,

    /* The updated at of the reward */
    @Json(name = "updated_at")
    val updatedAt: java.time.OffsetDateTime?

) {


}

