/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import com.winwinkit.client.models.User
import com.winwinkit.client.models.UserWithdrawCreditsResult

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param withdrawResult The withdraw result
 * @param user The user
 */


data class UserWithdrawCreditsResponseData (

    /* The withdraw result */
    @Json(name = "withdraw_result")
    val withdrawResult: UserWithdrawCreditsResult,

    /* The user */
    @Json(name = "user")
    val user: User

) {


}

