/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The stats of the user.
 *
 * @param claims The number of users who have claimed the referral code.
 * @param conversions The number of users who have converted to premium.
 * @param churns The number of users who have churned.
 */


data class UserStats (

    /* The number of users who have claimed the referral code. */
    @Json(name = "claims")
    val claims: kotlin.Int,

    /* The number of users who have converted to premium. */
    @Json(name = "conversions")
    val conversions: kotlin.Int,

    /* The number of users who have churned. */
    @Json(name = "churns")
    val churns: kotlin.Int

) {


}

