/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import com.winwinkit.client.models.UserAffiliateCode
import com.winwinkit.client.models.UserAffiliateStats

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The user's affiliate standing with this app.
 *
 * @param id The unique identifier of the affiliate.
 * @param status Where the affiliate stands with this app. `banned` is terminal; `rejected`, `withdrawn`, `archived` and `deactivated` describe affiliates who may apply again.
 * @param codes The codes the affiliate can currently promote, oldest first. Empty until they create one — an approved affiliate with no code yet is a normal state.
 * @param stats The affiliate's totals on this app.
 */
@JsonClass(generateAdapter = true)

data class UserAffiliate (

    /* The unique identifier of the affiliate. */
    @Json(name = "id")
    val id: kotlin.String,

    /* Where the affiliate stands with this app. `banned` is terminal; `rejected`, `withdrawn`, `archived` and `deactivated` describe affiliates who may apply again. */
    @Json(name = "status")
    val status: UserAffiliate.Status,

    /* The codes the affiliate can currently promote, oldest first. Empty until they create one — an approved affiliate with no code yet is a normal state. */
    @Json(name = "codes")
    val codes: kotlin.collections.List<UserAffiliateCode>,

    /* The affiliate's totals on this app. */
    @Json(name = "stats")
    val stats: UserAffiliateStats

) {

    /**
     * Where the affiliate stands with this app. `banned` is terminal; `rejected`, `withdrawn`, `archived` and `deactivated` describe affiliates who may apply again.
     *
     * Values: pending,withdrawn,approved,rejected,archived,deactivated,banned
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "pending") pending("pending"),
        @Json(name = "withdrawn") withdrawn("withdrawn"),
        @Json(name = "approved") approved("approved"),
        @Json(name = "rejected") rejected("rejected"),
        @Json(name = "archived") archived("archived"),
        @Json(name = "deactivated") deactivated("deactivated"),
        @Json(name = "banned") banned("banned");
    }

}

