/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param link The apply link to open, for the requested affiliate group or the app's default group. It carries a short-lived token identifying the user, so the affiliate they become is attributed back to them.
 */
@JsonClass(generateAdapter = true)

data class UserAffiliateApplyLinkResponseData (

    /* The apply link to open, for the requested affiliate group or the app's default group. It carries a short-lived token identifying the user, so the affiliate they become is attributed back to them. */
    @Json(name = "link")
    val link: kotlin.String

) {


}

