/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param groupSlug The affiliate group to apply to. Omit to link to the app's default group.
 */
@JsonClass(generateAdapter = true)

data class UserAffiliateApplyLinkRequest (

    /* The affiliate group to apply to. Omit to link to the app's default group. */
    @Json(name = "group_slug")
    val groupSlug: kotlin.String? = null

) {


}

