/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import com.winwinkit.client.models.User
import com.winwinkit.client.models.UserRewardsGranted

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param rewardsGranted The rewards granted to the user.
 * @param user The updated user.
 */


data class UserClaimCodeResponseData (

    /* The rewards granted to the user. */
    @Json(name = "rewards_granted")
    val rewardsGranted: UserRewardsGranted,

    /* The updated user. */
    @Json(name = "user")
    val user: User

) {


}

