/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import com.winwinkit.client.models.UserBasicRewardActive
import com.winwinkit.client.models.UserCreditRewardActive
import com.winwinkit.client.models.UserGooglePlayPromoCodeRewardActive
import com.winwinkit.client.models.UserOfferCodeRewardActive
import com.winwinkit.client.models.UserRevenueCatEntitlementRewardActive
import com.winwinkit.client.models.UserRevenueCatOfferingRewardActive

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param basic The referral user basic rewards
 * @param credit The referral user credit rewards
 * @param offerCode The referral user offer code rewards
 * @param googleplayPromoCode The referral user Google Play promo code rewards
 * @param revenuecatEntitlement The referral user RevenueCat entitlement rewards
 * @param revenuecatOffering The referral user RevenueCat offering rewards
 */


data class UserRewardsActive (

    /* The referral user basic rewards */
    @Json(name = "basic")
    val basic: kotlin.collections.List<UserBasicRewardActive>,

    /* The referral user credit rewards */
    @Json(name = "credit")
    val credit: kotlin.collections.List<UserCreditRewardActive>,

    /* The referral user offer code rewards */
    @Json(name = "offer_code")
    val offerCode: kotlin.collections.List<UserOfferCodeRewardActive>,

    /* The referral user Google Play promo code rewards */
    @Json(name = "googleplay_promo_code")
    val googleplayPromoCode: kotlin.collections.List<UserGooglePlayPromoCodeRewardActive>,

    /* The referral user RevenueCat entitlement rewards */
    @Json(name = "revenuecat_entitlement")
    val revenuecatEntitlement: kotlin.collections.List<UserRevenueCatEntitlementRewardActive>,

    /* The referral user RevenueCat offering rewards */
    @Json(name = "revenuecat_offering")
    val revenuecatOffering: kotlin.collections.List<UserRevenueCatOfferingRewardActive>

) {


}

