/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param purchaseToken Google Play's purchaseToken from the purchase flow.
 * @param obfuscatedExternalAccountId Set in BillingFlowParams.setObfuscatedAccountId() — used for better matching.
 */


data class UserRegisterGooglePlayTransactionRequest (

    /* Google Play's purchaseToken from the purchase flow. */
    @Json(name = "purchase_token")
    val purchaseToken: kotlin.String,

    /* Set in BillingFlowParams.setObfuscatedAccountId() — used for better matching. */
    @Json(name = "obfuscated_external_account_id")
    val obfuscatedExternalAccountId: kotlin.String? = null

) {


}

