/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param appUserId The unique identifier of the referral user in your app.
 * @param isTrial Whether the user is a trial user.
 * @param isPremium Whether the user is a premium user.
 * @param firstSeenAt The date when the user was first seen at.
 * @param lastSeenAt The date when the user was last seen at. Deprecated and will be removed in the future.
 * @param metadata The metadata of the user.
 * @param stripeCustomerId The unique identifier of the user in Stripe.
 */


data class UserCreateRequest (

    /* The unique identifier of the referral user in your app. */
    @Json(name = "app_user_id")
    val appUserId: kotlin.String,

    /* Whether the user is a trial user. */
    @Json(name = "is_trial")
    val isTrial: kotlin.Boolean? = null,

    /* Whether the user is a premium user. */
    @Json(name = "is_premium")
    val isPremium: kotlin.Boolean? = null,

    /* The date when the user was first seen at. */
    @Json(name = "first_seen_at")
    val firstSeenAt: java.time.OffsetDateTime? = null,

    /* The date when the user was last seen at. Deprecated and will be removed in the future. */
    @Json(name = "last_seen_at")
    @Deprecated(message = "This property is deprecated.")
    val lastSeenAt: java.time.OffsetDateTime? = null,

    /* The metadata of the user. */
    @Json(name = "metadata")
    val metadata: kotlin.Any? = null,

    /* The unique identifier of the user in Stripe. */
    @Json(name = "stripe_customer_id")
    val stripeCustomerId: kotlin.String? = null

) {


}

