/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param code The code to claim. Can be affiliate, promo or referral code.
 */


data class UserClaimCodeRequest (

    /* The code to claim. Can be affiliate, promo or referral code. */
    @Json(name = "code")
    val code: kotlin.String

) {


}

