/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The affiliate's totals on this app.
 *
 * @param claims The number of users who have claimed one of their codes.
 * @param conversions The number of users who have converted to premium.
 * @param earnings The commission accrued all-time, in USD cents. Gross and cumulative — not a balance, and not an amount available to withdraw.
 */
@JsonClass(generateAdapter = true)

data class UserAffiliateStats (

    /* The number of users who have claimed one of their codes. */
    @Json(name = "claims")
    val claims: kotlin.Int,

    /* The number of users who have converted to premium. */
    @Json(name = "conversions")
    val conversions: kotlin.Int,

    /* The commission accrued all-time, in USD cents. Gross and cumulative — not a balance, and not an amount available to withdraw. */
    @Json(name = "earnings")
    val earnings: kotlin.Int

) {


}

