/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param originalTransactionId Apple's originalTransactionId from StoreKit.
 * @param appAccountToken StoreKit 2 appAccountToken UUID.
 */


data class UserRegisterAppStoreTransactionRequest (

    /* Apple's originalTransactionId from StoreKit. */
    @Json(name = "original_transaction_id")
    val originalTransactionId: kotlin.String,

    /* StoreKit 2 appAccountToken UUID. */
    @Json(name = "app_account_token")
    val appAccountToken: kotlin.String? = null

) {


}

