/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import com.winwinkit.client.models.UserBasicRewardExpired
import com.winwinkit.client.models.UserCreditRewardExpired
import com.winwinkit.client.models.UserGooglePlayPromoCodeRewardExpired
import com.winwinkit.client.models.UserOfferCodeRewardExpired
import com.winwinkit.client.models.UserRevenueCatEntitlementRewardExpired
import com.winwinkit.client.models.UserRevenueCatOfferingRewardExpired

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param basic The referral user basic rewards
 * @param credit The referral user credit rewards
 * @param offerCode The referral user offer code rewards
 * @param googleplayPromoCode The referral user Google Play promo code rewards
 * @param revenuecatEntitlement The referral user RevenueCat entitlement rewards
 * @param revenuecatOffering The referral user RevenueCat offering rewards
 */


data class UserRewardsExpired (

    /* The referral user basic rewards */
    @Json(name = "basic")
    val basic: kotlin.collections.List<UserBasicRewardExpired>,

    /* The referral user credit rewards */
    @Json(name = "credit")
    val credit: kotlin.collections.List<UserCreditRewardExpired>,

    /* The referral user offer code rewards */
    @Json(name = "offer_code")
    val offerCode: kotlin.collections.List<UserOfferCodeRewardExpired>,

    /* The referral user Google Play promo code rewards */
    @Json(name = "googleplay_promo_code")
    val googleplayPromoCode: kotlin.collections.List<UserGooglePlayPromoCodeRewardExpired>,

    /* The referral user RevenueCat entitlement rewards */
    @Json(name = "revenuecat_entitlement")
    val revenuecatEntitlement: kotlin.collections.List<UserRevenueCatEntitlementRewardExpired>,

    /* The referral user RevenueCat offering rewards */
    @Json(name = "revenuecat_offering")
    val revenuecatOffering: kotlin.collections.List<UserRevenueCatOfferingRewardExpired>

) {


}

