/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A code the affiliate can promote on this app.
 *
 * @param code The affiliate code.
 * @param codeLink The shareable link for the code. Null when the app has turned code links off for the affiliate group.
 */
@JsonClass(generateAdapter = true)

data class UserAffiliateCode (

    /* The affiliate code. */
    @Json(name = "code")
    val code: kotlin.String,

    /* The shareable link for the code. Null when the app has turned code links off for the affiliate group. */
    @Json(name = "code_link")
    val codeLink: kotlin.String?

) {


}

