/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import com.winwinkit.client.models.UserRewardsActive
import com.winwinkit.client.models.UserRewardsExpired

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param active The referral user active rewards
 * @param expired The referral user expired rewards
 */


data class UserRewards (

    /* The referral user active rewards */
    @Json(name = "active")
    val active: UserRewardsActive,

    /* The referral user expired rewards */
    @Json(name = "expired")
    val expired: UserRewardsExpired

) {


}

