/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import com.winwinkit.client.models.OfferCodeReward
import com.winwinkit.client.models.OfferCodeValue

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param reward The reward
 * @param `value` The offer code value
 * @param expiresAt The expiration date of the reward
 * @param createdAt The created at of the reward
 * @param updatedAt The updated at of the reward
 */


data class UserOfferCodeRewardActive (

    /* The reward */
    @Json(name = "reward")
    val reward: OfferCodeReward,

    /* The offer code value */
    @Json(name = "value")
    val `value`: OfferCodeValue?,

    /* The expiration date of the reward */
    @Json(name = "expires_at")
    val expiresAt: java.time.OffsetDateTime?,

    /* The created at of the reward */
    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime,

    /* The updated at of the reward */
    @Json(name = "updated_at")
    val updatedAt: java.time.OffsetDateTime?

) {


}

