/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param creditsAvailableAtStart The amount of credits available at the start
 * @param creditsAvailableAtEnd The amount of credits available at the end
 * @param creditsRequestedToWithdraw The amount of credits requested to withdraw
 * @param creditsWithdrawn The amount of credits withdrawn
 */


data class UserWithdrawCreditsResult (

    /* The amount of credits available at the start */
    @Json(name = "credits_available_at_start")
    val creditsAvailableAtStart: kotlin.Int,

    /* The amount of credits available at the end */
    @Json(name = "credits_available_at_end")
    val creditsAvailableAtEnd: kotlin.Int,

    /* The amount of credits requested to withdraw */
    @Json(name = "credits_requested_to_withdraw")
    val creditsRequestedToWithdraw: kotlin.Int,

    /* The amount of credits withdrawn */
    @Json(name = "credits_withdrawn")
    val creditsWithdrawn: kotlin.Int

) {


}

