/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param key The key of the credit reward to withdraw
 * @param amount The amount of credits to withdraw
 * @param operationId An optional operation id that ensures the same operation won't be performed again
 */


data class UserWithdrawCreditsRequest (

    /* The key of the credit reward to withdraw */
    @Json(name = "key")
    val key: kotlin.String,

    /* The amount of credits to withdraw */
    @Json(name = "amount")
    val amount: kotlin.Int,

    /* An optional operation id that ensures the same operation won't be performed again */
    @Json(name = "operation_id")
    val operationId: kotlin.String? = null

) {


}

