/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The referred by of the user.
 *
 * @param code The code claimed by the user. Can be null if the code's entity has been deleted.
 * @param type The type of the code. Can be one of \"affiliate\", \"promo\", or \"referral\".
 */


data class UserReferredBy (

    /* The code claimed by the user. Can be null if the code's entity has been deleted. */
    @Json(name = "code")
    val code: kotlin.String?,

    /* The type of the code. Can be one of \"affiliate\", \"promo\", or \"referral\". */
    @Json(name = "type")
    val type: UserReferredBy.Type

) {

    /**
     * The type of the code. Can be one of \"affiliate\", \"promo\", or \"referral\".
     *
     * Values: affiliate,promo,referral
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "affiliate") affiliate("affiliate"),
        @Json(name = "promo") promo("promo"),
        @Json(name = "referral") referral("referral");
    }

}

