/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models

import com.winwinkit.client.models.ReferralProgram
import com.winwinkit.client.models.UserClaimCodeEligibility
import com.winwinkit.client.models.UserReferredBy
import com.winwinkit.client.models.UserRewards
import com.winwinkit.client.models.UserStats

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param appUserId The unique identifier of the user in your app.
 * @param referralCode The referral code of the user.
 * @param referralCodeLink The referral code link of the user.
 * @param isTrial Whether the user is a trial user.
 * @param isPremium Whether the user is a premium user.
 * @param firstSeenAt The date when the user was first seen at.
 * @param lastSeenAt The date when the user was last seen at. Deprecated, always returns null and will be removed in the future.
 * @param metadata The metadata of the user.
 * @param stripeCustomerId The unique identifier of the user in Stripe.
 * @param claimCodeEligibility The claim code eligibility of the user.
 * @param referredBy The referred by object of the user.
 * @param stats The stats of the user.
 * @param rewards The rewards of the user.
 * @param referralProgram The program of the user.
 */


data class User (

    /* The unique identifier of the user in your app. */
    @Json(name = "app_user_id")
    val appUserId: kotlin.String,

    /* The referral code of the user. */
    @Json(name = "referral_code")
    val referralCode: kotlin.String?,

    /* The referral code link of the user. */
    @Json(name = "referral_code_link")
    val referralCodeLink: kotlin.String?,

    /* Whether the user is a trial user. */
    @Json(name = "is_trial")
    val isTrial: kotlin.Boolean?,

    /* Whether the user is a premium user. */
    @Json(name = "is_premium")
    val isPremium: kotlin.Boolean?,

    /* The date when the user was first seen at. */
    @Json(name = "first_seen_at")
    val firstSeenAt: java.time.OffsetDateTime?,

    /* The date when the user was last seen at. Deprecated, always returns null and will be removed in the future. */
    @Json(name = "last_seen_at")
    @Deprecated(message = "This property is deprecated.")
    val lastSeenAt: java.time.OffsetDateTime?,

    /* The metadata of the user. */
    @Json(name = "metadata")
    val metadata: kotlin.Any?,

    /* The unique identifier of the user in Stripe. */
    @Json(name = "stripe_customer_id")
    val stripeCustomerId: kotlin.String?,

    /* The claim code eligibility of the user. */
    @Json(name = "claim_code_eligibility")
    val claimCodeEligibility: UserClaimCodeEligibility,

    /* The referred by object of the user. */
    @Json(name = "referred_by")
    val referredBy: UserReferredBy?,

    /* The stats of the user. */
    @Json(name = "stats")
    val stats: UserStats,

    /* The rewards of the user. */
    @Json(name = "rewards")
    val rewards: UserRewards,

    /* The program of the user. */
    @Json(name = "referral_program")
    val referralProgram: ReferralProgram?

) {


}

