/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * User's eligibility to claim referral code.
 *
 * @param eligible The claim code eligibility flag.
 * @param eligibleUntil The claim code eligibility until date.
 */


data class UserClaimCodeEligibility (

    /* The claim code eligibility flag. */
    @Json(name = "eligible")
    val eligible: kotlin.Boolean,

    /* The claim code eligibility until date. */
    @Json(name = "eligible_until")
    val eligibleUntil: java.time.OffsetDateTime?

) {


}

