/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.winwinkit.client.models.CodeResponse
import com.winwinkit.client.models.ErrorsResponse

import com.squareup.moshi.Json

import com.winwinkit.client.infrastructure.ApiClient
import com.winwinkit.client.infrastructure.ApiResponse
import com.winwinkit.client.infrastructure.ClientException
import com.winwinkit.client.infrastructure.ClientError
import com.winwinkit.client.infrastructure.ServerException
import com.winwinkit.client.infrastructure.ServerError
import com.winwinkit.client.infrastructure.MultiValueMap
import com.winwinkit.client.infrastructure.PartConfig
import com.winwinkit.client.infrastructure.RequestConfig
import com.winwinkit.client.infrastructure.RequestMethod
import com.winwinkit.client.infrastructure.ResponseType
import com.winwinkit.client.infrastructure.Success
import com.winwinkit.client.infrastructure.toMultiValue

class CodesApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "https://api.winwinkit.com")
        }
    }

    /**
     * GET /codes/{code}
     * Get Code
     * Resolves a code to its type (affiliate, promo or referral) and returns the relevant data for that type. Requires no app user id.
     * @param code The code to look up.
     * @param xApiKey The API key to authenticate with.
     * @return CodeResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getCode(code: kotlin.String, xApiKey: kotlin.String) : CodeResponse {
        val localVarResponse = getCodeWithHttpInfo(code = code, xApiKey = xApiKey)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CodeResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /codes/{code}
     * Get Code
     * Resolves a code to its type (affiliate, promo or referral) and returns the relevant data for that type. Requires no app user id.
     * @param code The code to look up.
     * @param xApiKey The API key to authenticate with.
     * @return ApiResponse<CodeResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getCodeWithHttpInfo(code: kotlin.String, xApiKey: kotlin.String) : ApiResponse<CodeResponse?> {
        val localVariableConfig = getCodeRequestConfig(code = code, xApiKey = xApiKey)

        return request<Unit, CodeResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getCode
     *
     * @param code The code to look up.
     * @param xApiKey The API key to authenticate with.
     * @return RequestConfig
     */
    fun getCodeRequestConfig(code: kotlin.String, xApiKey: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xApiKey.apply { localVariableHeaders["x-api-key"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/codes/{code}".replace("{"+"code"+"}", encodeURIComponent(code.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
