/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.winwinkit.client.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.winwinkit.client.models.ErrorsResponse
import com.winwinkit.client.models.UserCreateRequest
import com.winwinkit.client.models.UserResponse

import com.squareup.moshi.Json

import com.winwinkit.client.infrastructure.ApiClient
import com.winwinkit.client.infrastructure.ApiResponse
import com.winwinkit.client.infrastructure.ClientException
import com.winwinkit.client.infrastructure.ClientError
import com.winwinkit.client.infrastructure.ServerException
import com.winwinkit.client.infrastructure.ServerError
import com.winwinkit.client.infrastructure.MultiValueMap
import com.winwinkit.client.infrastructure.PartConfig
import com.winwinkit.client.infrastructure.RequestConfig
import com.winwinkit.client.infrastructure.RequestMethod
import com.winwinkit.client.infrastructure.ResponseType
import com.winwinkit.client.infrastructure.Success
import com.winwinkit.client.infrastructure.toMultiValue

class UsersApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "https://api.winwinkit.com")
        }
    }

    /**
     * POST /users
     * Create or Update User
     * Create or update a user if already exists.
     * @param xApiKey The API key to authenticate with.
     * @param userCreateRequest 
     * @return UserResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun createOrUpdateUser(xApiKey: kotlin.String, userCreateRequest: UserCreateRequest) : UserResponse {
        val localVarResponse = createOrUpdateUserWithHttpInfo(xApiKey = xApiKey, userCreateRequest = userCreateRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as UserResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /users
     * Create or Update User
     * Create or update a user if already exists.
     * @param xApiKey The API key to authenticate with.
     * @param userCreateRequest 
     * @return ApiResponse<UserResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun createOrUpdateUserWithHttpInfo(xApiKey: kotlin.String, userCreateRequest: UserCreateRequest) : ApiResponse<UserResponse?> {
        val localVariableConfig = createOrUpdateUserRequestConfig(xApiKey = xApiKey, userCreateRequest = userCreateRequest)

        return request<UserCreateRequest, UserResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createOrUpdateUser
     *
     * @param xApiKey The API key to authenticate with.
     * @param userCreateRequest 
     * @return RequestConfig
     */
    fun createOrUpdateUserRequestConfig(xApiKey: kotlin.String, userCreateRequest: UserCreateRequest) : RequestConfig<UserCreateRequest> {
        val localVariableBody = userCreateRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xApiKey.apply { localVariableHeaders["x-api-key"] = this.toString() }
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/users",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * GET /users/{app_user_id}
     * Get User
     * Retrieves a user by their app user id.
     * @param appUserId The app user id of the user to retrieve.
     * @param xApiKey The API key to authenticate with.
     * @return UserResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getUser(appUserId: kotlin.String, xApiKey: kotlin.String) : UserResponse {
        val localVarResponse = getUserWithHttpInfo(appUserId = appUserId, xApiKey = xApiKey)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as UserResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /users/{app_user_id}
     * Get User
     * Retrieves a user by their app user id.
     * @param appUserId The app user id of the user to retrieve.
     * @param xApiKey The API key to authenticate with.
     * @return ApiResponse<UserResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getUserWithHttpInfo(appUserId: kotlin.String, xApiKey: kotlin.String) : ApiResponse<UserResponse?> {
        val localVariableConfig = getUserRequestConfig(appUserId = appUserId, xApiKey = xApiKey)

        return request<Unit, UserResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getUser
     *
     * @param appUserId The app user id of the user to retrieve.
     * @param xApiKey The API key to authenticate with.
     * @return RequestConfig
     */
    fun getUserRequestConfig(appUserId: kotlin.String, xApiKey: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xApiKey.apply { localVariableHeaders["x-api-key"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/users/{app_user_id}".replace("{"+"app_user_id"+"}", encodeURIComponent(appUserId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
